<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductCategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('product_categories')->truncate();
        DB::table('product_categories')->insert([

            array(
                "id" => 1,
                "product_id" => 4,
                "name" => "VANNAMEI HEAD ON SHELL ON SHRIMPS",
                "scientific_name" => "Litopenaeus vannamei",
                "forms" => "BLOCK FROZEN, SEMI IQF & IQF",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "10/20, 20/30, 30/40, 40/50, 50/60, 60/70, 70/80, 80/100.",
                "packing" => "0 x 1kg, 6 x 2 kg, 1 X 10kg bulk (in poly bag, duplex box & Carton)",
                "description" => "",
                "path" => "new_look/images/product/HOSO-VN.jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 2,
                "product_id" => 4,
                "name" => "VANNAMEI HEADLESS SHRIMPS",
                "scientific_name" => "Litopenaeus vannamei",
                "forms" => "IQF & BLOCK FROZEN",
                "price" => NULL,
                "origin" => "India",
                "features" => NULL,
                "order_size" => "8/12, 13/15, 16/20, 21/25, 26/30, 31/40, 41/50, 51/60, 61/70, 71/90, 91/110.",
                "packing" => "10 x 1kg, 6 x 2 kg, 1 X 10kg bulk (in poly bag, duplex box & Carton)",
                "description" => NULL,
                "path" => "new_look/images/product/V-HL RAW.jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 3,
                "product_id" => 4,
                "name" => "VANNAMEI PEELED & DEVEINED TAIL ON SHRIMPS",
                "scientific_name" => "Litopenaeus vannamei",
                "forms" => "IQF & BLOCK FROZEN",
                "price" => NULL,
                "origin" => "India",
                "features" => NULL,
                "order_size" => "8/12, 13/15, 16/20, 21/25, 26/30, 31/40, 41/50, 51/60, 61/70, 71/90.",
                "packing" => "10 x 1kg, 5 X 2kg, 1 X 10kg bulk (in poly bag & Carton)",
                "description" => NULL,
                "path" => "new_look/images/product/V-PDTO RAW.jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 4,
                "product_id" => 4,
                "name" => "VANNAMEI PEELED & DEVEINED SHRIMPS",
                "scientific_name" => "Litopenaeus vannamei",
                "forms" => "IQF & BLOCK FROZEN",
                "price" => NULL,
                "origin" => "India",
                "features" => NULL,
                "order_size" => "8/12, 13/15, 16/20, 21/25, 26/30, 31/40, 41/50, 51/60, 61/70, 71/90.",
                "packing" => "10 x 1kg, 5 X 2kg, 1 X 10kg bulk (in poly bag & Carton)",
                "description" => NULL,
                "path" => "new_look/images/product/V-PD RAW.jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 5,
                "product_id" => 4,
                "name" => "VANNAMEI COOKED PEELED & DEVEINED TAIL ON SHRIMPS",
                "scientific_name" => "Litopenaeus vannamei",
                "forms" => "IQF",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "8/12, 13/15, 16/20, 21/25, 26/30, 31/40, 41/50, 51/60, 61/70, 71/90.",
                "packing" => "10 x 1kg, 5 X 2kg, 1 X 10kg bulk (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/Loading_2.gif",
                "status" => 0,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 6,
                "product_id" => 4,
                "name" => "BLACK TIGER HEAD ON SHELL ON SHRIMPS",
                "scientific_name" => "Penaeus monodon",
                "forms" => "BLOCK FROZEN, SEMI IQF & IQF.",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "U/5, U/7, U/10, U/15, 10/20, 20/30, 30/40, 40/50, 50/60, 60/70, 70/80, 80/100.",
                "packing" => "10 x 1kg, 6 x 2 kg, 1 X 10kg bulk (in poly bag, duplex box & Carton)",
                "description" => "",
                "path" => "new_look/images/product/Loading_2.gif",
                "status" => 0,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 7,
                "product_id" => 4,
                "name" => "BLACK TIGER HEADLESS SHRIMPS",
                "scientific_name" => "Penaeus monodon",
                "forms" => "IQF & BLOCK FROZEN",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "4/6, 6/8, 8/12, 13/15, 16/20, 21/25, 26/30, 31/40, 41/50, 51/60, 61/70, 71/90.",
                "packing" => "10 x 1kg, 6 x 2 kg, 1 X 10kg bulk (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/black_tiger-7.jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 8,
                "product_id" => 4,
                "name" => "SEA TIGER HEAD ON SHELL ON SHRIMPS",
                "scientific_name" => "Penaeus monodon",
                "forms" => "BLOCK FROZEN, SEMI IQF & IQF.",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "U/5, U/7, U/10, U/15, 10/20, 20/30, 30/40, 40/50.",
                "packing" => "10 x 1kg, 6 x 2 kg, 1 X 10kg bulk (in poly bag, duplex box & Carton)",
                "description" => "",
                "path" => "new_look/images/product/ST-HEAD ON.jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 9,
                "product_id" => 4,
                "name" => "SEA TIGER HEADLESS SHRIMPS",
                "scientific_name" => "Penaeus monodon",
                "forms" => "IQF & BLOCK FROZEN",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "4/6, 6/8, 8/12, 13/15, 16/20, 21/25, 26/30, 31/40, 41/50, 51/60, 61/70, 71/90.",
                "packing" => "10 x 1kg, 6 x 2 kg, 1 X 10kg bulk (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/ST-HL.jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 10,
                "product_id" => 4,
                "name" => "SEA WHITE HEAD ON SHELL ON SHRIMPS ",
                "scientific_name" => "Fenneropenaeus indicus",
                "forms" => "BLOCK FROZEN, SEMI IQF & IQF.",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "U/5, U/7, U/10, U/15, 10/20, 20/30, 30/40, 40/50, 50/60.",
                "packing" => "10 x 1kg, 6 x 2 kg, 1 X 10kg bulk (in poly bag, duplex box & Carton)",
                "description" => "",
                "path" => "new_look/images/product/WHITE- HEAD ON.jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 11,
                "product_id" => 4,
                "name" => "SEA WHITE HEADLESS SHRIMPS",
                "scientific_name" => "Fenneropenaeus indicus",
                "forms" => "IQF & BLOCK FROZEN",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "4/6, 6/8, 8/12, 13/15, 16/20, 21/25, 26/30, 31/40, 41/50, 51/60, 61/70, 71/90.",
                "packing" => "10 x 1kg, 6 x 2 kg, 1 X 10kg bulk (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/Loading_2.gif",
                "status" => 0,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 12,
                "product_id" => 4,
                "name" => "ROCK LOBSTER WHOLE",
                "scientific_name" => "Panulirus polyphagus, Panulirus homarus",
                "forms" => "IQF",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "300/400, 400/500, 500/600, 600/700, 700/800, 800/900, 900/1000, 1000/UP.",
                "packing" => " 1 X 10kg bulk, 2 X 5kg (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/ROCK LOBSTER-12.jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 13,
                "product_id" => 4,
                "name" => "ROCK LOBSTER TAIL",
                "scientific_name" => "Panulirus polyphagus, Panulirus homarus",
                "forms" => "IQF",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "50/80, 80/100, 100/150, 150/200, 200/UP & U/1, 1/2, 2/4, 4/6, 6/8, 8/12.",
                "packing" => "1 X 10kg bulk, 2 X 5kg (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/RLT.jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 14,
                "product_id" => 4,
                "name" => "SAND LOBSTER",
                "scientific_name" => "Thenus orientails",
                "forms" => "IQF",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "100/150, 150/200, 200/300, 300/400, 400/500, 500/UP",
                "packing" => "1 X 10kg bulk, 2 X 5kg (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/SAND LOBSTER-14.jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 15,
                "product_id" => 4,
                "name" => "COOKED ROCK LOBSTER",
                "scientific_name" => "Panulirus polyphagus, Panulirus homarus",
                "forms" => "IQF",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "200/300, 300/400, 400/500, 500/600, 600/700, 700/800, 800/900, 900/1000, 1000/UP.",
                "packing" => " 1 X 10kg bulk, 2 X 5kg (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/COOKED.jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 16,
                "product_id" => 4,
                "name" => "FRESHWATER PRAWN- SCAMPI",
                "scientific_name" => "Macrobrachium rosenbergii",
                "forms" => "IQF",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "U/3, U/5, U/7, U/10, U/15, 16/20, 21/25.",
                "packing" => "1 X 10kg bulk, 5 X 2kg (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/IMG_0045.JPG",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 17,
                "product_id" => 5,
                "name" => "SQUID WHOLE",
                "scientific_name" => "Loligo duvaucelii, Uroteothis duvaucelii",
                "forms" => "IQF & BLOCK FROZEN",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "U/3, 3/6, 6/10, 10/20, 20/30, 30/40, 40/60.",
                "packing" => "10 X 1kg, 6 X 2kg (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/SQW.jpg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 18,
                "product_id" => 5,
                "name" => "SQUID WHOLE CLEAN",
                "scientific_name" => "Loligo duvaucelii, Uroteothis duvaucelii",
                "forms" => "IQF & BLOCK FROZEN",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "U/3, 3/6, 6/10, 10/20, 20/30, 30/40, 40/60.",
                "packing" => "10 X 1kg, 6 X 2kg (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/SQUID WHOLE CLEAN-18.jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 19,
                "product_id" => 5,
                "name" => "SQUID TUBES",
                "scientific_name" => "Loligo duvaucelii, Uroteothis duvaucelii",
                "forms" => "IQF & BLOCK FROZEN",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "U/3, U/10, 10/20, 20/30, 30/40, 40/60.",
                "packing" => "10 X 1kg, 6 X 2kg (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/SQUID TUBES.jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 20,
                "product_id" => 5,
                "name" => "SQUID TENTACLES",
                "scientific_name" => "Loligo duvaucelii, Uroteothis duvaucelii",
                "forms" => "IQF",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "As per customer requirements.",
                "packing" => " 10 X 1kg, 1 X 10kg  (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/IMG_  (2).jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 21,
                "product_id" => 5,
                "name" => "CUT SQUID",
                "scientific_name" => "Loligo duvaucelii, Uroteothis duvaucelii",
                "forms" => "IQF",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "As per customer requirements.",
                "packing" => " 10 X 1kg, 1 X 10kg  (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/Loading_2.gif",
                "status" => 0,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 22,
                "product_id" => 5,
                "name" => "CUTTLEFISH WHOLE",
                "scientific_name" => "Sepia pharaonis",
                "forms" => "IQF & BLOCK FROZEN",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "300/500, 500/700, 700/1000, 1000/UP",
                "packing" => "2 X 10kg (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/CFW.jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 23,
                "product_id" => 5,
                "name" => "BABY CUTTLEFISH WHOLE",
                "scientific_name" => "Sepia pharaonis",
                "forms" => "IQF & BLOCK FROZEN",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "10/20, 20/30, 30/50, 50/100,100/200, 200/300.",
                "packing" => "2 X 10kg, 4 X 5kg(in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/B.CFW.JPG",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 24,
                "product_id" => 5,
                "name" => "CUTTLEFISH WHOLE CLEAN",
                "scientific_name" => "Sepia pharaonis",
                "forms" => "IQF & BLOCK FROZEN",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "U/1, 1/2, 2/4, 4/6, 6/8, 8/12, 12/15, 10/20.",
                "packing" => "2 X 10kg, 4 X 5kg (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/Loading_2.gif",
                "status" => 0,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 25,
                "product_id" => 5,
                "name" => "OCTOPUS WHOLE CLEAN",
                "scientific_name" => "Octopus vulgaris",
                "forms" => "IQF & BLOCK FROZEN",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "5/15, 16/25, 26/40, 40/60, 60/UP.",
                "packing" => "10 X 1kg, 10 X 2lbs (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/OCTOPUS WHOLE CLEAN.jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 26,
                "product_id" => 5,
                "name" => "OCTOPUS WHOLE ",
                "scientific_name" => "Octopus vulgaris",
                "forms" => "IQF & BLOCK FROZEN",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "4’’/UP, 5’’/UP, 6’’/UP",
                "packing" => " 20 X 500gm , 10 X 1KG (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/OCTOPUS WHOLE.jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 27,
                "product_id" => 9,
                "name" => "TILAPIA WHOLE",
                "scientific_name" => "Oreochromis mossambicus",
                "forms" => "IQF",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "80/100, 100/200, 200/300, 300/500, 500/800, 800/1000, 1000/UP",
                "packing" => "1 X 10kg, 2 X 5KG (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/Loading_2.gif",
                "status" => 0,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 28,
                "product_id" => 9,
                "name" => "TILAPIA GUTTED",
                "scientific_name" => "Oreochromis mossambicus",
                "forms" => "IQF",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "80/100, 100/200, 200/300, 300/500, 500/800, 800/1000, 1000/UP",
                "packing" => "1 X 10kg, 2 X 5KG (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/TILAPIA GTD.JPG",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 29,
                "product_id" => 9,
                "name" => "TENGRA FISH",
                "scientific_name" => "Mystus tengra",
                "forms" => "IQF & BLOCK FROZEN",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "80/100, 100/200, 200/300, 300/500, 500/800, 800/1000, 1000/UP",
                "packing" => "1 X 10kg, 2 X 5KG (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/TENGRA WHOLE RAW.jpeg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 30,
                "product_id" => 9,
                "name" => "PABDA FISH",
                "scientific_name" => "Ompok pabda",
                "forms" => "IQF & BLOCK FROZEN",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "7’’/UP, 9’’/UP",
                "packing" => "20 X 500gm , 10 X 1KG (in poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/Ompok pabda raw.jpg",
                "status" => 1,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),
            array(
                "id" => 31,
                "product_id" => 9,
                "name" => "BOAL FISH GUTTED",
                "scientific_name" => "Wallago attu",
                "forms" => "IQF",
                "price" => "",
                "origin" => "India",
                "features" => NULL,
                "order_size" => "1-1.5kg, 1.5-2kg, 2-3kg, 3-5kg, 5kg/UP.",
                "packing" => " 1 X 20kg (in IWP poly bag & Carton)",
                "description" => "",
                "path" => "new_look/images/product/Loading_2.gif",
                "status" => 0,
                "created_by" => 0,
                "updated_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
                "deleted_at" => NULL,
            ),


        ]);
    }
}
